### ISSUE TITLE
👋 Clarification request

### ISSUE THREAD

**Issue by ehawman** [nokibsarkar/sqlite3-incremental-backup#2]
Hey! Thank you for creating this tool. I haven't played with it quite yet but I was a little curious as to how your snapshot naming conventions go.

Let's say I wanted to do a full backup on Sun, then incremental backups on Mon, Tues, Wed, etc.

So on Sunday I do my first backup, a full backup. `/source/my.db` >>> `/dest/my.db`

End of day Monday, your script sees that I've added a single record to `my.db`, does its hashy things, and saves that info to `mydb_mon.txt` in `/dest/`. 

Tuesday, your script... does a differential backup based off the difference between `/source/my.db` and `/dest/my.db`? Scans `/dest/` for other files and guesses which increment order they go in? What happens here that makes it incremental? Is it saving to `mydb_tues.txt`?

Thanks again 😄

**Comment by nokibsarkar** [comment]
> So on Sunday I do my first backup, a full backup. /source/my.db >>> /dest/my.db

The naming convention is arbitrary ( you would provide the name for the snapshot file). If you leave the name blank, it will generate a snapshot name as `snapshot-*{current-date}*.txt`. So, at `2022-06-21T12:59:59` (Sunday), the snapshot name would be like `snapshot-2022-06-21T12:59:59.txt`. And, the tool (or library) would save the database as chunks into the `objectDirectory` (can be arbitrary) and would keep the relative path of those chunks in that snapshot file named `snapshot-2022-06-21T12:59:59.txt`.

> End of day Monday, your script sees that I've added a single record to my.db, does its hashy things, and saves that info to mydb_mon.txt in /dest/.

At end of the Monday, it would again divide the database into several chunks and backup those which were changed. after that, it would save the relative path of the chunks into another snapshot named as `snapshot-2022-06-22T12:59:59.txt`.

Remember, the snapshot name can be given manually, in that case, you have to make sure there is no collision.
