### ISSUE TITLE
Why GPL?

### ISSUE THREAD

**Issue by guettli** [nokibsarkar/sqlite3-incremental-backup#3]
Why did you choose the GPL.

This means I must not use it.

**Comment by nokibsarkar** [comment]
Can you describe your use case and which term is preventing you from using this?

**Comment by guettli** [comment]
The GPL is viral. In my current context only MIT/Apache/BSD licences are allowed. Sorry, can't tell you more at the moment.

**Comment by nokibsarkar** [comment]
MIT chosen
